### ISSUE TITLE
Evaluation on Unsupervised Semantic Segmentation Benchmarks

### ISSUE THREAD

**Issue by Haochen-Wang409** [CVMI-Lab/SlotCon#4]
Hi, @xwen99 great work on unsupervised local features learning.

I am wondering how to evaluate SlotCon on unsupervised semantic segmentation benchmarks (i.e., Table 5 in the paper).
Do you have any plans to release the implementation?

**Comment by xwen99** [comment]
Hi @Haochen-Wang409, thank you for your interest in our work.
Since this work mainly focuses on representation learning and does not aim to propose a SOTA for unsupervised semantic segmentation, currently, we do not plan to release the code for this task.
However, if you are really interested in the evaluation of unsupervised semantic segmentation, we have provided detailed implementation settings in section A.3 of the appendix. Concerning implementation, our experimental code is based on PiCIE (https://github.com/janghyuncho/PiCIE), and the modification is quite small.

**Comment by Haochen-Wang409** [comment]
Thanks for your prompt reply!
